### PR TITLE
Defconrelease

### PR DESCRIPTION
**Pull request by psc4re**
Changes include updates presented at Defcon 31.

### CODE REVIEW

**Comment by podjackel** [comment]
Testing this branch I ran into a couple of issues:
* `tools/alertmonitor/alertmon.sh`, line 2 `cd /home/asf/alerts/`
  * There is no prevision for establishing, or need it appears, for an `asf` user. Maybe should move it to `/var/log/asf` ?
* After making the above change, restarting the `asf` service, the web server doesn't appear to come up.
* `kubectl` installation should probably be checked prescript to give time for installation before trying to start pods.

```
┌──(root㉿kali)-[/opt/asf]
└─# apt update
Hit:1 http://kali.download/kali kali-rolling InRelease
Get:2 https://packages.cloud.google.com/apt kubernetes-xenial InRelease [8993 B]
Err:2 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
Reading package lists... Done
W: GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
E: The repository 'https://apt.kubernetes.io kubernetes-xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Just wanted to note these down real fast.

**Comment by psc4re** [comment]
@podjackel try checking the ASF service using `systemctl status asf.service` . feel free to share the details of the error if required.

**Comment by podjackel** [comment]
I don't see anything blatant standing out, everything appears to be running, but the web server never starts listening. To keep the install more or less clean, I manually created the `/home/asf/alerts` directory.

If I get time will do another fresh install and see who it's operating post install & pre reboot.
```
┌──(root㉿kali)-[~]
└─# systemctl status asf.service
● asf.service - Attack Surface Framework
     Loaded: loaded (/etc/systemd/system/asf.service; enabled; preset: disabled)
     Active: active (running) since Thu 2023-08-24 12:47:37 UTC; 3min 59s ago
   Main PID: 551 (gunicorn)
      Tasks: 6 (limit: 38499)
     Memory: 129.9M
        CPU: 1.261s
     CGroup: /system.slice/asf.service
             ├─ 551 /opt/asf/frontend/asfui/bin/python3 /opt/asf/frontend/asfui//bin/gunicorn core.wsgi:application --name asfui --workers 3 --bind=unix:/opt/asf/frontend/asfui/>
             ├─ 553 /bin/bash /opt/asf/tools/alertmonitor/alertmon.sh
             ├─ 582 /opt/asf/frontend/asfui/bin/python3 /opt/asf/frontend/asfui//bin/gunicorn core.wsgi:application --name asfui --workers 3 --bind=unix:/opt/asf/frontend/asfui/>
             ├─ 583 /opt/asf/frontend/asfui/bin/python3 /opt/asf/frontend/asfui//bin/gunicorn core.wsgi:application --name asfui --workers 3 --bind=unix:/opt/asf/frontend/asfui/>
             ├─ 588 /opt/asf/frontend/asfui/bin/python3 /opt/asf/frontend/asfui//bin/gunicorn core.wsgi:application --name asfui --workers 3 --bind=unix:/opt/asf/frontend/asfui/>
             └─1266 sleep 2

Aug 24 12:47:37 kali systemd[1]: Started asf.service - Attack Surface Framework.
Aug 24 12:47:37 kali startasf.sh[551]: Starting asfui as root

┌──(root㉿kali)-[~]
└─# netstat -plant
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      576/sshd: /usr/sbin
tcp        0      0 127.0.0.1:44767         0.0.0.0:*               LISTEN      571/containerd
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      785/docker-proxy
tcp        0    312 172.31.57.225:22        x.x.x.2:26911       ESTABLISHED 1090/sshd: kali [pr
tcp6       0      0 :::22                   :::*                    LISTEN      576/sshd: /usr/sbin
tcp6       0      0 :::27017                :::*                    LISTEN      791/docker-proxy

┌──(root㉿kali)-[~]
└─# tail /opt/asf/frontend/asfui/logs/*
==> /opt/asf/frontend/asfui/logs/gunicorn.log <==
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-08-24 12:47:38 +0000] [551] [INFO] Starting gunicorn 21.2.0
[2023-08-24 12:47:38 +0000] [551] [DEBUG] Arbiter booted
[2023-08-24 12:47:38 +0000] [551] [INFO] Listening at: unix:/opt/asf/frontend/asfui//gunicorn.sock (551)
[2023-08-24 12:47:38 +0000] [551] [INFO] Using worker: sync
[2023-08-24 12:47:38 +0000] [582] [INFO] Booting worker with pid: 582
[2023-08-24 12:47:38 +0000] [583] [INFO] Booting worker with pid: 583
[2023-08-24 12:47:38 +0000] [588] [INFO] Booting worker with pid: 588
[2023-08-24 12:47:38 +0000] [551] [DEBUG] 3 workers

==> /opt/asf/frontend/asfui/logs/nginx-access.log <==

==> /opt/asf/frontend/asfui/logs/nginx-error.log <==
```

**Comment by podjackel** [comment]
Ok, did a fresh install. Steps taken:

* Cloned repo to `/opt/asf`
* copied `backup.env.prod` to `.env.prod`
* ran `setup.sh`
* skipped using kubernetes

The web server does come up, but not accessible.

```
┌──(root㉿kali)-[/opt/asf/frontend/asfui/logs]
└─# systemctl status asf.service
● asf.service - Attack Surface Framework
     Loaded: loaded (/etc/systemd/system/asf.service; enabled; preset: disabled)
     Active: active (running) since Thu 2023-08-24 13:26:36 UTC; 17min ago
   Main PID: 6400 (gunicorn)
      Tasks: 6 (limit: 38499)
     Memory: 114.4M
        CPU: 9.231s
     CGroup: /system.slice/asf.service
             ├─6400 /opt/asf/frontend/asfui/bin/python3 /opt/asf/frontend/asfui//bin/gunicorn core.wsgi:application --name asfui --workers 3 --bind=unix:/opt/asf/frontend/asfui/>
             ├─6405 /bin/bash /opt/asf/tools/alertmonitor/alertmon.sh
             ├─7154 /opt/asf/frontend/asfui/bin/python3 /opt/asf/frontend/asfui//bin/gunicorn core.wsgi:application --name asfui --workers 3 --bind=unix:/opt/asf/frontend/asfui/>
             ├─7810 /opt/asf/frontend/asfui/bin/python3 /opt/asf/frontend/asfui//bin/gunicorn core.wsgi:application --name asfui --workers 3 --bind=unix:/opt/asf/frontend/asfui/>
             ├─7822 /opt/asf/frontend/asfui/bin/python3 /opt/asf/frontend/asfui//bin/gunicorn core.wsgi:application --name asfui --workers 3 --bind=unix:/opt/asf/frontend/asfui/>
             └─7984 sleep 2

Aug 24 13:26:36 kali systemd[1]: Started asf.service - Attack Surface Framework.
Aug 24 13:26:36 kali startasf.sh[6405]: /opt/asf/tools/alertmonitor/alertmon.sh: line 2: cd: /home/asf/alerts/: No such file or directory
Aug 24 13:26:36 kali startasf.sh[6400]: Starting asfui as root
┌──(root㉿kali)-[/opt/asf/frontend/asfui/logs]
└─# netstat -plant
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:42401         0.0.0.0:*               LISTEN      4661/containerd
tcp        0      0 0.0.0.0:2021            0.0.0.0:*               LISTEN      6514/nginx: master
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      689/sshd: /usr/sbin
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      5946/docker-proxy
tcp        0      0 172.31.90.73:22         x.x.x.x:34751       ESTABLISHED 7481/sshd: kali [pr
tcp        0    312 172.31.90.73:22         x.x.x.x:31124       ESTABLISHED 837/sshd: kali [pri
tcp6       0      0 :::22                   :::*                    LISTEN      689/sshd: /usr/sbin
tcp6       0      0 :::27017                :::*                    LISTEN      5952/docker-proxy

┌──(root㉿kali)-[/opt/asf/frontend/asfui/logs]
└─# curl http://127.0.0.1:2021/
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.24.0</center>
</body>
</html>

┌──(root㉿kali)-[/opt/asf/frontend/asfui/logs]
└─# tail *
==> gunicorn.log <==
[2023-08-24 13:42:04 +0000] [6400] [CRITICAL] WORKER TIMEOUT (pid:6442)
[2023-08-24 13:42:04 +0000] [6442] [INFO] Worker exiting (pid: 6442)
[2023-08-24 13:42:04 +0000] [6400] [ERROR] Worker (pid:6442) exited with code 1
[2023-08-24 13:42:04 +0000] [6400] [ERROR] Worker (pid:6442) exited with code 1.
[2023-08-24 13:42:04 +0000] [7810] [INFO] Booting worker with pid: 7810
[2023-08-24 13:42:14 +0000] [6400] [CRITICAL] WORKER TIMEOUT (pid:6938)
[2023-08-24 13:42:14 +0000] [6938] [INFO] Worker exiting (pid: 6938)
[2023-08-24 13:42:14 +0000] [6400] [ERROR] Worker (pid:6938) exited with code 1
[2023-08-24 13:42:14 +0000] [6400] [ERROR] Worker (pid:6938) exited with code 1.
[2023-08-24 13:42:14 +0000] [7822] [INFO] Booting worker with pid: 7822

==> nginx-access.log <==
127.0.0.1 - - [24/Aug/2023:13:31:16 +0000] "GET / HTTP/1.1" 404 187 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
127.0.0.1 - - [24/Aug/2023:13:31:46 +0000] "GET /favicon.ico HTTP/1.1" 404 187 "http://127.0.0.1:2021/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
127.0.0.1 - - [24/Aug/2023:13:31:54 +0000] "GET /admin HTTP/1.1" 404 187 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
127.0.0.1 - - [24/Aug/2023:13:33:48 +0000] "GET / HTTP/1.1" 404 187 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
127.0.0.1 - - [24/Aug/2023:13:41:41 +0000] "GET / HTTP/1.1" 499 0 "-" "curl/7.88.1"
127.0.0.1 - - [24/Aug/2023:13:42:14 +0000] "GET / HTTP/1.1" 404 153 "-" "curl/7.88.1"

==> nginx-error.log <==
2023/08/24 13:31:16 [error] 6515#6515: *1 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://unix:/opt/asf/frontend/asfui/gunicorn.sock:/", host: "127.0.0.1:2021"
2023/08/24 13:31:16 [error] 6515#6515: *1 open() "/opt/asf/frontend/asfui/core/static/500.html" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://unix:/opt/asf/frontend/asfui/gunicorn.sock/", host: "127.0.0.1:2021"
2023/08/24 13:31:46 [error] 6515#6515: *1 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/opt/asf/frontend/asfui/gunicorn.sock:/favicon.ico", host: "127.0.0.1:2021", referrer: "http://127.0.0.1:2021/"
2023/08/24 13:31:46 [error] 6515#6515: *1 open() "/opt/asf/frontend/asfui/core/static/500.html" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/opt/asf/frontend/asfui/gunicorn.sock/favicon.ico", host: "127.0.0.1:2021", referrer: "http://127.0.0.1:2021/"
2023/08/24 13:31:54 [error] 6516#6516: *4 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /admin HTTP/1.1", upstream: "http://unix:/opt/asf/frontend/asfui/gunicorn.sock:/admin", host: "127.0.0.1:2021"
2023/08/24 13:31:54 [error] 6516#6516: *4 open() "/opt/asf/frontend/asfui/core/static/500.html" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /admin HTTP/1.1", upstream: "http://unix:/opt/asf/frontend/asfui/gunicorn.sock/admin", host: "127.0.0.1:2021"
2023/08/24 13:33:48 [error] 6517#6517: *6 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://unix:/opt/asf/frontend/asfui/gunicorn.sock:/", host: "127.0.0.1:2021"
2023/08/24 13:33:48 [error] 6517#6517: *6 open() "/opt/asf/frontend/asfui/core/static/500.html" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://unix:/opt/asf/frontend/asfui/gunicorn.sock/", host: "127.0.0.1:2021"
2023/08/24 13:42:14 [error] 6520#6520: *10 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://unix:/opt/asf/frontend/asfui/gunicorn.sock:/", host: "127.0.0.1:2021"
2023/08/24 13:42:14 [error] 6520#6520: *10 open() "/opt/asf/frontend/asfui/core/static/500.html" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://unix:/opt/asf/frontend/asfui/gunicorn.sock/", host: "127.0.0.1:2021"
```

Checking the install output it looks like there are some python issues around like 1372.

[install-log.txt](https://github.com/vmware-labs/attack-surface-framework/files/12430032/install-log.txt)

**Pull request closed without merging**
